// dev/react/src/components/remoteComponent.js
import React from 'react';
import {
  hooks,
  esModule,
  loadModule,
  setModuleConfig,
} from '@garfish/remote-module';
import { remoteComponentUrl } from '../config';

setModuleConfig({
  externals: { React },
  alias: { Component: remoteComponentUrl },
});

const RemoteComponent = React.lazy(() => {
  return esModule(loadModule('@Component.One'));
});

hooks.usePlugin({
  name: 'devTest',
  asyncBeforeLoadModule(data) {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(data);
      }, 1000);
    });
  },
});

export default function RemoteCp() {
  return (
    <div>
      <h3 data-test="title">React sub App remote component</h3>
      <React.Suspense fallback={<div>loading</div>}>
        <div>
          <RemoteComponent text="cool!" />
        </div>
      </React.Suspense>
    </div>
  );
}

// dev/vue/src/components/remoteComponent.vue
<template>
  <div id="remote-component">
    <h3 data-test="title">Vue App remote component</h3>
    <cm-one :text="text"/>
    <cm-two :text="text"/>
    <el-button data-test="change-data" plain @click="changeData">
      切换数据
    </el-button>
  </div>
</template>

<script>
import {
  loadModule,
  setModuleConfig,
} from '@garfish/remote-module';

setModuleConfig({
  alias: {
    Component: 'http://localhost:9090/remoteModule.js',
  },
})

export default {
  name: 'remoteComponent',
  props: ['basename'],
  data: () => ({
    text: 'old text',
  }),
  methods: {
    changeData() {
      this.text = this.text === 'old text' ? 'new text' : 'old text'
    }
  },
  components: {
    cmOne: () => loadModule('@Component.cmOne'),
    cmTwo: () => loadModule('@Component.cmTwo'),
  }
}
</script>
